#ifndef MEFESTPLUGIN_GLOBAL_H
#define MEFESTPLUGIN_GLOBAL_H

#include <QtGlobal>

#if defined(MEFESTPLUGIN_LIBRARY)
#  define MEFESTPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MEFESTPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MEFESTPLUGIN_GLOBAL_H
