build:
  # указываем образ в котором будет происходить сборка
  image: darkmattercoder/qt-build

  # указываем команды для сборки
  script:
   - qmake -makefile
   - make

  # загружаем собранные файлы в gitlab
  artifacts:
    paths:
     - ./build
